require "digest/md5"

require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :test do
  puts "executando uma tarefa de teste"
end

task :local_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

  users = [
    { name: "Roberto Carlos", email: "betao@yahoo.com.br", password: to_md5("pwd123") },
    { name: "Akaua", email: "claudino@bol.com", password: to_md5("pwd123") },
    { name: "Anderson neves", email: "spider@hotmail.com", password: to_md5("pwd123") },
    { name: "João Anunciante", email: "joao@anunciante.com", password: to_md5("pwd123") },
    { name: "Maria Locataria", email: "maria@locataria.com", password: to_md5("pwd123") },
  ]
  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber"
end

task :hmg_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))

  users = [
    { name: "Roberto Carlos", email: "betao@yahoo.com.br", password: to_md5("pwd123") },
    { name: "Akaua", email: "claudino@bol.com", password: to_md5("pwd123") },
  ]
  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)
end
